services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hiready_network

  backend:
    image: ghcr.io/dwi-wahyu/hiready-backend:latest
    build: ./backend
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      GROQ_API_KEY: ${GROQ_API_KEY}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL}
      ORIGIN: ${ORIGIN}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    depends_on:
      - postgres
    networks:
      - hiready_network

  frontend:
    image: ghcr.io/dwi-wahyu/hiready-frontend:latest
    build: ./frontend
    restart: unless-stopped
    env_file: .env
    environment:
      PUBLIC_BACKEND_URL: ${PUBLIC_BACKEND_URL}
      PUBLIC_BACKEND_WS: ${PUBLIC_BACKEND_WS}
    ports:
      - "5000:5000"
    depends_on:
      - backend
    networks:
      - hiready_network

volumes:
  postgres_data:

networks:
  hiready_network:
