services:
  # Database Service (PostgreSQL - Matched with Drizzle & Backend dependencies)
  db:
    image: postgres:15-alpine
    container_name: hiready_database
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5002"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend Service (FastAPI)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hiready_backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
      MODEL_PATH: ${MODEL_PATH}
    expose:
      - "5001"
    volumes:
      - model_cache:/app/models # Hanya cache model yang perlu persist

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hiready_frontend
    restart: always
    depends_on:
      - backend

    environment:
      DATABASE_URL: ${DATABASE_URL}
      PUBLIC_BACKEND_URL: ${PUBLIC_BACKEND_URL}
      PUBLIC_BACKEND_WS: ${PUBLIC_BACKEND_WS}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL}
      ORIGIN: ${ORIGIN}
      GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
      GOOGLE_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET}"
      PORT: ${FRONTEND_PORT}
      HOST: 0.0.0.0
    ports:
      - "5000:5000"

volumes:
  postgres_data:
  model_cache:
