version: "3.8"

services:
  # ==========================================
  # DATABASE (POSTGRES)
  # ==========================================
  db:
    image: docker.io/library/postgres:16-alpine
    container_name: heurix-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /var/www/heurix/data/postgres_data:/var/lib/postgresql/data
    ports:
      - 5002:5432
    restart: always

  # ==========================================
  # MIGRATOR (Jalan sekali sampai sukses)
  # ==========================================
  migrator:
    image: ghcr.io/dwi-wahyu/heurix-migrator:latest
    container_name: heurix-migrator
    environment:
      # Di compose, kita tembak host 'db', bukan 'localhost'
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db

  # ==========================================
  # BACKEND (FASTAPI)
  # ==========================================
  backend:
    image: ghcr.io/dwi-wahyu/heurix-backend:latest
    container_name: heurix-backend
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      GROQ_API_KEY: ${GROQ_API_KEY}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL}
      ORIGIN: ${ORIGIN}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      MODEL_PATH: /app/models
    ports:
      - 5001:8000
    restart: always

  # ==========================================
  # FRONTEND (SVELTEKIT)
  # ==========================================
  frontend:
    image: ghcr.io/dwi-wahyu/heurix-frontend:latest
    container_name: heurix-frontend
    environment:
      PUBLIC_BACKEND_URL: ${PUBLIC_BACKEND_URL}
      PUBLIC_BACKEND_WS: ${PUBLIC_BACKEND_WS}
      PORT: ${FRONTEND_PORT}
    ports:
      - 5000:5000 # Sesuai nodePort kamu sebelumnya (akses lewat port 30000)
    depends_on:
      - migrator
    restart: always
